[mypy]
python_version = "3.13"
warn_return_any = true
ignore_missing_imports = true

# Qt type stubs are incomplete
[mypy-PyQt6.*]
ignore_errors = true

[mypy-netscope.widgets.*]
disable_error_code = union-attr

[mypy-netscope.windows.*]
disable_error_code = union-attr